function fetchWithRetry(url,attempt=1,retries=5){
    return new Promise((resolve,reject)=>{
        fetch(url)
        .then(resolve =>(resolve.json()))
        .then((result => console.log(result)))
        .catch(
            error =>{
                if(attempt<retries)
                {
                    console.log("Attemp failed retrying");
                    fetchWithRetry(url,attempt+1,retries)
                    .then(resolve)
                    .catch(reject)
                }
                else{
                    console.log("Error,try again later")
                }
            }
        )
    })
}
fetchWithRetry('https://fakestoreapi.com/products')
.then(result =>(console.log(result)))
.catch(error =>(console.log(error)))
