async function fetchWithRetry(url, retries, delay = 1000) {
    for (let attempt = 0; attempt <= retries; attempt++) {
        try {
            const response = await fetch(url);
            if (!response.ok) {
                throw new Error(`Not able to fetch data :"Error"`);
            }
            const data = await response.json();
            return data;
        } catch (error) {
            if (attempt < retries) {
                console.log(`Attempt  failed. Retrying ...`);
                await new Promise(resolve => setTimeout(resolve, delay));
            } else {
                throw new Error(`Failed after attempts`);
            }
        }
    }
}

fetchWithRetry('https://fakestoreapi.com/products', 5)
    .then(data => console.log('Data fetched successfully:', data))
    .catch(error => console.error('Error fetching data:', error));
